
#GITHUB ACTIONS PIPELINE
name: Pipeline for Tests Automation in Java

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE deliverydb;' -u root -p
#          mysql -e 'CREATE DATABASE deliverydb-test;' -u root -proot

      - name: Build with Maven
        run: |
          mvn -B verify --file pom.xml
          mvn -B clean package --file pom.xml
        #sudo systemctl start mysql.service
